server:
  port: 8086

spring:
  data:
    redis:
      cluster:
        nodes: redis-node-1:7000,redis-node-2:7001,redis-node-3:7002,redis-node-4:7003,redis-node-5:7004,redis-node-6:7005
        max-redirects: 3
      password: ""
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  jpa:
    show-sql: false

storage:
  minio:
    endpoint: http://minio:9000
    access-key: keepguard_admin
    secret-key: keepguard_minio_2025_secure

logging:
  level:
    root: WARN
    com.keepguard: INFO
  logstash:
    host: ${LOGGING_LOGSTASH_HOST:localhost}
    port: ${LOGGING_LOGSTASH_PORT:5000}
    enabled: ${LOGGING_LOGSTASH_ENABLED:true}

