server:
  port: 8586

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keepguard_api_db
    username: keepguard_api_user
    password: keepguard_api_pass
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

storage:
  minio:
    endpoint: http://localhost:9000

